### ISSUE TITLE
Make spinner optional

### ISSUE THREAD

**Issue by jmatsushita** [stevenvachon/broken-link-checker#26]
Hi there,

There's some prior talk about problems with spinners here: https://github.com/npm/npm/issues/5340

Would be great to make it optional! Will send a PR.

Jun

**Comment by stevenvachon** [comment]
What problem does a spinner cause? I see someone in that linked issue mentioning mocha, but using this library with a testing framework would either require the use of a child process, which doesn't automatically log to the parent or using the programmatic API which doesn't log anything.

I had thought about adding status text next to the spinner, to show what is currently happening.

**Comment by lvillani** [comment]
It creates a lot of garbage output in e.g. Travis output log: https://travis-ci.org/lvillani/lvillani.github.io/builds/192185424

**Comment by lvillani** [comment]
Merging PR #27 goes a long way to make blc's output more readable. Stuff that changes cursor position/erases characters should be disabled unless attached to a TTY. Ideally, colors should be disabled too, unless the process is attached to a TTY, since that breaks e.g. Jenkins (and many other CI solutions) output logging unless a plugin to interpret ANSI escape codes is installed.

**Comment by stevenvachon** [comment]
[char-spinner](https://npmjs.com/char-spinner) should already disable itself in non-TTY contexts, according to its source code. [chalk](https://npmjs.com/chalk), however, doesn't seem to have such a feature.

**Comment by stevenvachon** [comment]
I may add in a `--no-colors` option to disable the spinner, which will also automatically disable colors in the color module. May also use [supports-color](https://npmjs.com/supports-color).

**Comment by lvillani** [comment]
For whatever reason Travis launches commands with an attached TTY (i.e.: running `node -e 'console.log(process.stderr.isTTY)'` prints `true`). This is why both char-spinner and chalk don't disable themselves. Travis supports colored output so chalk isn't a problem here (and it would still work correctly e.g. on Jenkins, which AFAIK doesn't attach a TTY to the child process).

However, Travis' log viewer can't cope with the way char-spinner erases characters though, because it's not a standard TTY. It seems to be a [long-standing](https://github.com/travis-ci/travis-ci/issues/1337) issue on their part.

I think disabling the spinner when we detect the `CONTINUOUS_INTEGRATION` environment variable or with a config switch (by merging #27 by @jmatsushita) would be sufficient.

**Comment by stevenvachon** [comment]
I think detecting `CONTINUOUS_INTEGRATION` would be better. I'd prefer not to load up the CLI with options when we don't need to. It's already got a bunch of options and will only get more as the functionality increases in complexity.

**Comment by stevenvachon** [comment]
The v0.8 branch has the spinner replaced with the progress bar that npm uses. and both of these env vars as conditions to exclude.
